name: Tag Beta

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check for release version
      uses: actions/github-script@v2
      id: check
      with:
        script: |
          const { owner, repo } = context.repo
          const regex = /\d+\.\d+\.\d+\.\d+/g;
          if (regex.test(`${{ github.event.head_commit.message }}`)) {
            const run_id = "${{ github.run_id }}";
            await github.actions.cancelWorkflowRun({ owner, repo, run_id });
          } else {
            return "build"
          }
        result-encoding: string

  tag:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: --no-color -q
        annotate: warning

    - name: Check variables
      run: |
        echo ${{ github.event }}
        echo ${{ github.event.head_commit.message }}
        echo ${{ github.event_name }}
        echo ${{ github.event_path }}
        echo ${{ github.ref }}

    - name: Set beta
      uses: onemedical/action-general-autotag@main
      with:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        source_file: "Aurora.toc"
        extraction_regex: "\\s*##\\s*Version\\s*:\\s*(\\d+\\.\\d+\\.\\d+.\\d+)"
        tag_format: "{version}.${{ github.run_number }}-beta"
        tag_message: "beta"
